export const   LOGIN_REQUEST = 'LOGIN_REQUEST';
export const   LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const   LOGIN_FAILD = 'LOGIN_FAILD';


export const   REGISTER_REQUEST = 'REGISTER_REQUEST';
export const   REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const   REGISTER_FAILD = 'REGISTER_FAILD';

export const  CLEAR_ERROR = 'CLEAR_ERROR';

